[project]
name = "fluidbench"
version = "0.1.0"
description = "CFD benchmark tool for fluids"
authors = [{name = "sp-droid"}]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "h5py>=3.16.0",
    "huggingface-hub>=2.0.0",
    "ipykernel==6.30.1",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.11.2",
    "numba-cuda-mlir[cu13]>=0.5.3",
    "numpy>=2.5.3",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "tqdm>=4.70.1",
]

[tool.uv.build-backend]
module-name = "fluidbench"

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch-cu132" }

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true
